import Link from "next/link";
import "./globals.css"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="navbar">
          <Link href="/" className="logo">AppleForum</Link>
          <Link href="/list">List</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
