import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/">홈</Link>
          <Link href="/basic">1. nextJs 기본</Link>
          <Link href="/route">2. 라우트</Link>
          <Link href="/mapFuc">3. map함수</Link>
          <Link href="/insertImg">4. 이미지 추가</Link>
          <Link href="/list">0. 프로젝트-list</Link>
          <Link href="/cart">0. 프로젝트-cart</Link>
          <Link href="/cart/payment">0. 프로젝트-payment</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
