import Link from "next/link";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="navbar">
          <Link href="/">홈</Link>
          <Link href="/list">상품</Link>
          <Link href="/cart">장바구니</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
